namespace ExcelMate
{
    using System.Drawing;
    using System.Windows.Forms;
    using System;
    using Mac.Excel9.Interop;
    using System.ComponentModel;
    using System.Diagnostics;

    partial class mExcelMate
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(mExcelMate));
            this.bnSaveLeft = new System.Windows.Forms.Button();
            this.tbLeftRaw = new System.Windows.Forms.TextBox();
            this.openFileDialog1 = new OpenFileDialog();
            this.bnOpenWorkBook = new System.Windows.Forms.Button();
            this.tbFileName = new System.Windows.Forms.TextBox();
            this.cbWorkSheet = new ComboBox();
            this.cbRound = new ComboBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.tbRightReaction = new System.Windows.Forms.TextBox();
            this.cbRigthRider = new ComboBox();
            this.bnSaveRight = new System.Windows.Forms.Button();
            this.tbRightRaw = new System.Windows.Forms.TextBox();
            this.tbLeftReaction = new System.Windows.Forms.TextBox();
            this.cbLeftRider = new ComboBox();
            this.cbComPort = new ComboBox();
            this.label5 = new System.Windows.Forms.Label();
            this.bnConnect = new System.Windows.Forms.Button();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.cbRightColor = new ComboBox();
            this.cbLeftColor = new ComboBox();
            this.cbColors = new System.Windows.Forms.CheckBox();
            this.cbLog2File = new System.Windows.Forms.CheckBox();
            this.button1 = new System.Windows.Forms.Button();
            this.cbSingleLanePort = new System.Windows.Forms.CheckBox();
            this.cbDiscardReactionTimes = new System.Windows.Forms.CheckBox();
            this.bnHelp = new System.Windows.Forms.Button();
            this.label12 = new System.Windows.Forms.Label();
            this.tbReporterId = new System.Windows.Forms.TextBox();
            this.cbDisplays = new System.Windows.Forms.CheckBox();
            this.label15 = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.tbEventId = new System.Windows.Forms.TextBox();
            this.bnConnectDisplays = new System.Windows.Forms.Button();
            this.cbDisplayPortLeft = new ComboBox();
            this.cbLiveReport = new System.Windows.Forms.CheckBox();
            this.cbDisplayPortRight = new ComboBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.cbLayOut = new System.Windows.Forms.CheckBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.cbLeftCones = new ComboBox();
            this.cbRightCones = new ComboBox();
            this.process1 = new Process();
            this.tbPrevData = new System.Windows.Forms.TextBox();
            this.cbPreviousData = new System.Windows.Forms.CheckBox();
            this.bnReset = new System.Windows.Forms.Button();
            this.tabControl1 = new TabControl();
            this.tabSettings = new TabPage();
            this.tabRace = new TabPage();
            this.groupRight = new System.Windows.Forms.GroupBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.groupLeft = new System.Windows.Forms.GroupBox();
            this.bnRefreshList = new System.Windows.Forms.Button();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.tabControl1.SuspendLayout();
            this.tabSettings.SuspendLayout();
            this.tabRace.SuspendLayout();
            this.groupRight.SuspendLayout();
            this.groupLeft.SuspendLayout();
            base.SuspendLayout();
            this.bnSaveLeft.BackColor = Color.WhiteSmoke;
            this.bnSaveLeft.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.bnSaveLeft.ForeColor = Color.Black;
            this.bnSaveLeft.Location = new System.Drawing.Point(0x290, 8);
            this.bnSaveLeft.Margin = new Padding(2, 3, 2, 3);
            this.bnSaveLeft.Name = "bnSaveLeft";
            this.bnSaveLeft.Size = new Size(0x6d, 0x2b);
            this.bnSaveLeft.TabIndex = 10;
            this.bnSaveLeft.Text = "Save";
            this.bnSaveLeft.UseVisualStyleBackColor = false;
            this.bnSaveLeft.Click += new EventHandler(this.bnSaveLeft_Click);
            this.tbLeftRaw.BackColor = Color.White;
            this.tbLeftRaw.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.tbLeftRaw.ForeColor = Color.Black;
            this.tbLeftRaw.Location = new System.Drawing.Point(0x1c3, 0x10);
            this.tbLeftRaw.Margin = new Padding(2, 3, 2, 3);
            this.tbLeftRaw.Name = "tbLeftRaw";
            this.tbLeftRaw.Size = new Size(0x57, 0x1f);
            this.tbLeftRaw.TabIndex = 3;
            this.tbLeftRaw.TabStop = false;
            this.tbLeftRaw.TextChanged += new EventHandler(this.ShowFinalTimeOnDisplayLeft);
            this.openFileDialog1.FileName = "openFileDialog1";
            this.bnOpenWorkBook.Location = new System.Drawing.Point(0x102, 0x22);
            this.bnOpenWorkBook.Margin = new Padding(2, 3, 2, 3);
            this.bnOpenWorkBook.Name = "bnOpenWorkBook";
            this.bnOpenWorkBook.Size = new Size(100, 0x17);
            this.bnOpenWorkBook.TabIndex = 3;
            this.bnOpenWorkBook.TabStop = false;
            this.bnOpenWorkBook.Text = "Select Excel file";
            this.bnOpenWorkBook.UseVisualStyleBackColor = true;
            this.bnOpenWorkBook.Click += new EventHandler(this.bnOpenWorkBook_Click);
            this.tbFileName.BackColor = Color.White;
            this.tbFileName.ForeColor = Color.Black;
            this.tbFileName.Location = new System.Drawing.Point(8, 0x23);
            this.tbFileName.Margin = new Padding(2, 3, 2, 3);
            this.tbFileName.Name = "tbFileName";
            this.tbFileName.Size = new Size(0xf3, 20);
            this.tbFileName.TabIndex = 4;
            this.tbFileName.TabStop = false;
            this.cbWorkSheet.BackColor = Color.White;
            this.cbWorkSheet.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cbWorkSheet.ForeColor = Color.Black;
            this.cbWorkSheet.FormattingEnabled = true;
            this.cbWorkSheet.Location = new System.Drawing.Point(0x86, 0x3b);
            this.cbWorkSheet.Margin = new Padding(2, 3, 2, 3);
            this.cbWorkSheet.Name = "cbWorkSheet";
            this.cbWorkSheet.Size = new Size(0x76, 0x15);
            this.cbWorkSheet.TabIndex = 5;
            this.cbWorkSheet.TabStop = false;
            this.cbWorkSheet.SelectedIndexChanged += new EventHandler(this.cbWorkSheet_SelectedIndexChanged);
            this.cbRound.BackColor = Color.White;
            this.cbRound.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cbRound.Enabled = false;
            this.cbRound.ForeColor = Color.Black;
            this.cbRound.FormattingEnabled = true;
            this.cbRound.Location = new System.Drawing.Point(0x86, 0x54);
            this.cbRound.Margin = new Padding(2, 3, 2, 3);
            this.cbRound.Name = "cbRound";
            this.cbRound.Size = new Size(0x76, 0x15);
            this.cbRound.TabIndex = 6;
            this.cbRound.TabStop = false;
            this.cbRound.SelectedIndexChanged += new EventHandler(this.cbRound_SelectedIndexChanged);
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(7, 0x3e);
            this.label1.Margin = new Padding(2, 0, 2, 0);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x7a, 13);
            this.label1.TabIndex = 7;
            this.label1.Text = "Please select worksheet";
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(7, 0x55);
            this.label2.Margin = new Padding(2, 0, 2, 0);
            this.label2.Name = "label2";
            this.label2.Size = new Size(100, 13);
            this.label2.TabIndex = 8;
            this.label2.Text = "Please select round";
            this.tbRightReaction.BackColor = Color.White;
            this.tbRightReaction.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.tbRightReaction.ForeColor = Color.Black;
            this.tbRightReaction.Location = new System.Drawing.Point(370, 0x10);
            this.tbRightReaction.Margin = new Padding(2, 3, 2, 3);
            this.tbRightReaction.Name = "tbRightReaction";
            this.tbRightReaction.Size = new Size(0x4b, 0x1f);
            this.tbRightReaction.TabIndex = 7;
            this.tbRightReaction.TabStop = false;
            this.cbRigthRider.BackColor = Color.White;
            this.cbRigthRider.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cbRigthRider.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cbRigthRider.ForeColor = Color.Black;
            this.cbRigthRider.FormattingEnabled = true;
            this.cbRigthRider.Location = new System.Drawing.Point(6, 0x10);
            this.cbRigthRider.Margin = new Padding(2, 3, 2, 3);
            this.cbRigthRider.Name = "cbRigthRider";
            this.cbRigthRider.Size = new Size(0x166, 0x20);
            this.cbRigthRider.TabIndex = 6;
            this.bnSaveRight.BackColor = Color.WhiteSmoke;
            this.bnSaveRight.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.bnSaveRight.ForeColor = Color.Black;
            this.bnSaveRight.Location = new System.Drawing.Point(0x290, 0x34);
            this.bnSaveRight.Margin = new Padding(2, 3, 2, 3);
            this.bnSaveRight.Name = "bnSaveRight";
            this.bnSaveRight.Size = new Size(0x6d, 0x22);
            this.bnSaveRight.TabIndex = 10;
            this.bnSaveRight.Text = "Save Right";
            this.bnSaveRight.UseVisualStyleBackColor = false;
            this.bnSaveRight.Visible = false;
            this.tbRightRaw.BackColor = Color.White;
            this.tbRightRaw.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.tbRightRaw.ForeColor = Color.Black;
            this.tbRightRaw.Location = new System.Drawing.Point(0x1c3, 0x10);
            this.tbRightRaw.Margin = new Padding(2, 3, 2, 3);
            this.tbRightRaw.Name = "tbRightRaw";
            this.tbRightRaw.Size = new Size(0x57, 0x1f);
            this.tbRightRaw.TabIndex = 8;
            this.tbRightRaw.TabStop = false;
            this.tbRightRaw.TextChanged += new EventHandler(this.ShowFinalTimeOnDisplayRight);
            this.tbLeftReaction.BackColor = Color.White;
            this.tbLeftReaction.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.tbLeftReaction.ForeColor = Color.Black;
            this.tbLeftReaction.Location = new System.Drawing.Point(370, 0x10);
            this.tbLeftReaction.Margin = new Padding(2, 3, 2, 3);
            this.tbLeftReaction.Name = "tbLeftReaction";
            this.tbLeftReaction.Size = new Size(0x4b, 0x1f);
            this.tbLeftReaction.TabIndex = 2;
            this.tbLeftReaction.TabStop = false;
            this.cbLeftRider.BackColor = Color.White;
            this.cbLeftRider.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cbLeftRider.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cbLeftRider.ForeColor = Color.Black;
            this.cbLeftRider.FormattingEnabled = true;
            this.cbLeftRider.Location = new System.Drawing.Point(6, 0x10);
            this.cbLeftRider.Margin = new Padding(2, 3, 2, 3);
            this.cbLeftRider.Name = "cbLeftRider";
            this.cbLeftRider.Size = new Size(0x166, 0x20);
            this.cbLeftRider.TabIndex = 1;
            this.cbComPort.BackColor = Color.White;
            this.cbComPort.ForeColor = Color.Black;
            this.cbComPort.FormattingEnabled = true;
            this.cbComPort.Location = new System.Drawing.Point(0xa8, 10);
            this.cbComPort.Margin = new Padding(2, 3, 2, 3);
            this.cbComPort.Name = "cbComPort";
            this.cbComPort.Size = new Size(0x54, 0x15);
            this.cbComPort.TabIndex = 0x13;
            this.cbComPort.TabStop = false;
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(7, 14);
            this.label5.Margin = new Padding(2, 0, 2, 0);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x9b, 13);
            this.label5.TabIndex = 20;
            this.label5.Text = "Select COM port for TrackMate";
            this.bnConnect.BackColor = Color.WhiteSmoke;
            this.bnConnect.ForeColor = Color.Black;
            this.bnConnect.Location = new System.Drawing.Point(0x102, 9);
            this.bnConnect.Margin = new Padding(2, 3, 2, 3);
            this.bnConnect.Name = "bnConnect";
            this.bnConnect.Size = new Size(100, 0x17);
            this.bnConnect.TabIndex = 0x15;
            this.bnConnect.TabStop = false;
            this.bnConnect.Text = "Connect!";
            this.bnConnect.UseVisualStyleBackColor = false;
            this.bnConnect.Click += new EventHandler(this.bnConnect_Click_1);
            this.groupBox1.BackColor = Color.White;
            this.groupBox1.Controls.Add(this.cbRightColor);
            this.groupBox1.Controls.Add(this.cbLeftColor);
            this.groupBox1.Controls.Add(this.cbColors);
            this.groupBox1.Controls.Add(this.cbLog2File);
            this.groupBox1.Controls.Add(this.button1);
            this.groupBox1.Controls.Add(this.cbSingleLanePort);
            this.groupBox1.Controls.Add(this.cbDiscardReactionTimes);
            this.groupBox1.Controls.Add(this.bnHelp);
            this.groupBox1.Controls.Add(this.label12);
            this.groupBox1.Controls.Add(this.tbReporterId);
            this.groupBox1.Controls.Add(this.cbDisplays);
            this.groupBox1.Controls.Add(this.label15);
            this.groupBox1.Controls.Add(this.label10);
            this.groupBox1.Controls.Add(this.label16);
            this.groupBox1.Controls.Add(this.label11);
            this.groupBox1.Controls.Add(this.tbEventId);
            this.groupBox1.Controls.Add(this.bnConnectDisplays);
            this.groupBox1.Controls.Add(this.cbDisplayPortLeft);
            this.groupBox1.Controls.Add(this.cbLiveReport);
            this.groupBox1.Controls.Add(this.cbDisplayPortRight);
            this.groupBox1.ForeColor = Color.Black;
            this.groupBox1.Location = new System.Drawing.Point(0x17b, -2);
            this.groupBox1.Margin = new Padding(2, 3, 2, 3);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Padding = new Padding(2, 3, 2, 3);
            this.groupBox1.Size = new Size(0x1fa, 0x6c);
            this.groupBox1.TabIndex = 0x16;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Advanced";
            this.cbRightColor.FormattingEnabled = true;
            object[] items = new object[] { "Right", "White", "Red", "Green", "Orange", "Blue", "Yellow" };
            this.cbRightColor.Items.AddRange(items);
            this.cbRightColor.Location = new System.Drawing.Point(0xe0, 0x54);
            this.cbRightColor.Margin = new Padding(2, 3, 2, 3);
            this.cbRightColor.Name = "cbRightColor";
            this.cbRightColor.Size = new Size(0x3f, 0x15);
            this.cbRightColor.TabIndex = 0x2f;
            this.cbLeftColor.FormattingEnabled = true;
            object[] objArray2 = new object[] { "Left", "White", "Red", "Green", "Orange", "Blue", "Yellow" };
            this.cbLeftColor.Items.AddRange(objArray2);
            this.cbLeftColor.Location = new System.Drawing.Point(0x97, 0x54);
            this.cbLeftColor.Margin = new Padding(2, 3, 2, 3);
            this.cbLeftColor.Name = "cbLeftColor";
            this.cbLeftColor.Size = new Size(0x3f, 0x15);
            this.cbLeftColor.TabIndex = 0x2e;
            this.cbColors.AutoSize = true;
            this.cbColors.Location = new System.Drawing.Point(6, 0x57);
            this.cbColors.Margin = new Padding(2, 3, 2, 3);
            this.cbColors.Name = "cbColors";
            this.cbColors.Size = new Size(0x80, 0x11);
            this.cbColors.TabIndex = 0x2d;
            this.cbColors.Text = "Use colorbased lanes";
            this.cbColors.UseVisualStyleBackColor = true;
            this.cbColors.CheckedChanged += new EventHandler(this.cbColors_CheckedChanged);
            this.cbLog2File.AutoSize = true;
            this.cbLog2File.Checked = true;
            this.cbLog2File.CheckState = CheckState.Checked;
            this.cbLog2File.Location = new System.Drawing.Point(6, 0x3e);
            this.cbLog2File.Margin = new Padding(2, 3, 2, 3);
            this.cbLog2File.Name = "cbLog2File";
            this.cbLog2File.Size = new Size(0x90, 0x11);
            this.cbLog2File.TabIndex = 0x2c;
            this.cbLog2File.Text = "Log recorded times to file";
            this.cbLog2File.UseVisualStyleBackColor = true;
            this.button1.Location = new System.Drawing.Point(0x97, 0x3a);
            this.button1.Margin = new Padding(2, 3, 2, 3);
            this.button1.Name = "button1";
            this.button1.Size = new Size(0x3e, 0x17);
            this.button1.TabIndex = 0x2a;
            this.button1.TabStop = false;
            this.button1.Text = "Logfile";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new EventHandler(this.bnLogfile_Click);
            this.cbSingleLanePort.AutoSize = true;
            this.cbSingleLanePort.Location = new System.Drawing.Point(6, 0x26);
            this.cbSingleLanePort.Margin = new Padding(2, 3, 2, 3);
            this.cbSingleLanePort.Name = "cbSingleLanePort";
            this.cbSingleLanePort.Size = new Size(0x11a, 0x11);
            this.cbSingleLanePort.TabIndex = 0x2b;
            this.cbSingleLanePort.Text = "Use Right lane port on Trackmate in single lane racing";
            this.cbSingleLanePort.UseVisualStyleBackColor = true;
            this.cbDiscardReactionTimes.AutoSize = true;
            this.cbDiscardReactionTimes.Location = new System.Drawing.Point(6, 14);
            this.cbDiscardReactionTimes.Margin = new Padding(2, 3, 2, 3);
            this.cbDiscardReactionTimes.Name = "cbDiscardReactionTimes";
            this.cbDiscardReactionTimes.Size = new Size(130, 0x11);
            this.cbDiscardReactionTimes.TabIndex = 0x2a;
            this.cbDiscardReactionTimes.Text = "Discard reaction times";
            this.cbDiscardReactionTimes.UseVisualStyleBackColor = true;
            this.bnHelp.BackColor = Color.WhiteSmoke;
            this.bnHelp.ForeColor = Color.Black;
            this.bnHelp.Location = new System.Drawing.Point(0x1bb, 0x53);
            this.bnHelp.Margin = new Padding(2, 3, 2, 3);
            this.bnHelp.Name = "bnHelp";
            this.bnHelp.Size = new Size(0x38, 0x17);
            this.bnHelp.TabIndex = 0x29;
            this.bnHelp.Text = "Help";
            this.bnHelp.UseVisualStyleBackColor = false;
            this.bnHelp.Click += new EventHandler(this.bnCheckId_Click);
            this.label12.AutoSize = true;
            this.label12.ForeColor = Color.Black;
            this.label12.Location = new System.Drawing.Point(0xfe, 0x10);
            this.label12.Margin = new Padding(2, 0, 2, 0);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x20, 13);
            this.label12.TabIndex = 40;
            this.label12.Text = "Right";
            this.label12.Visible = false;
            this.tbReporterId.BackColor = Color.White;
            this.tbReporterId.Enabled = false;
            this.tbReporterId.ForeColor = Color.Black;
            this.tbReporterId.Location = new System.Drawing.Point(0x180, 0x1c);
            this.tbReporterId.Margin = new Padding(2, 3, 2, 3);
            this.tbReporterId.Name = "tbReporterId";
            this.tbReporterId.Size = new Size(0x37, 20);
            this.tbReporterId.TabIndex = 0x24;
            this.tbReporterId.Visible = false;
            this.cbDisplays.AutoSize = true;
            this.cbDisplays.ForeColor = Color.Black;
            this.cbDisplays.Location = new System.Drawing.Point(0x143, 10);
            this.cbDisplays.Margin = new Padding(2, 3, 2, 3);
            this.cbDisplays.Name = "cbDisplays";
            this.cbDisplays.Size = new Size(0xb0, 0x11);
            this.cbDisplays.TabIndex = 0x21;
            this.cbDisplays.Text = "Send times to external display(s)";
            this.cbDisplays.UseVisualStyleBackColor = true;
            this.cbDisplays.Visible = false;
            this.cbDisplays.CheckedChanged += new EventHandler(this.cbDisplays_CheckedChanged);
            this.label15.AutoSize = true;
            this.label15.Location = new System.Drawing.Point(0x141, 0x20);
            this.label15.Margin = new Padding(2, 0, 2, 0);
            this.label15.Name = "label15";
            this.label15.Size = new Size(0x3f, 13);
            this.label15.TabIndex = 0x23;
            this.label15.Text = "Reporter Id:";
            this.label15.Visible = false;
            this.label10.AutoSize = true;
            this.label10.ForeColor = Color.Black;
            this.label10.Location = new System.Drawing.Point(5, 0x20);
            this.label10.Margin = new Padding(2, 0, 2, 0);
            this.label10.Name = "label10";
            this.label10.Size = new Size(180, 13);
            this.label10.TabIndex = 0x25;
            this.label10.Text = "Select COM port for external displays";
            this.label10.Visible = false;
            this.label16.AutoSize = true;
            this.label16.BackColor = Color.White;
            this.label16.ForeColor = Color.Black;
            this.label16.Location = new System.Drawing.Point(0x142, 0x36);
            this.label16.Margin = new Padding(2, 0, 2, 0);
            this.label16.Name = "label16";
            this.label16.Size = new Size(0x2c, 13);
            this.label16.TabIndex = 0x25;
            this.label16.Text = "EventId";
            this.label16.Visible = false;
            this.label11.AutoSize = true;
            this.label11.ForeColor = Color.Black;
            this.label11.Location = new System.Drawing.Point(0xbc, 0x10);
            this.label11.Margin = new Padding(2, 0, 2, 0);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x19, 13);
            this.label11.TabIndex = 0x27;
            this.label11.Text = "Left";
            this.label11.Visible = false;
            this.tbEventId.BackColor = Color.White;
            this.tbEventId.Enabled = false;
            this.tbEventId.ForeColor = Color.Black;
            this.tbEventId.Location = new System.Drawing.Point(0x180, 0x33);
            this.tbEventId.Margin = new Padding(2, 3, 2, 3);
            this.tbEventId.Name = "tbEventId";
            this.tbEventId.Size = new Size(0x37, 20);
            this.tbEventId.TabIndex = 0x22;
            this.tbEventId.Visible = false;
            this.bnConnectDisplays.BackColor = Color.WhiteSmoke;
            this.bnConnectDisplays.ForeColor = Color.Black;
            this.bnConnectDisplays.Location = new System.Drawing.Point(0x143, 0x1b);
            this.bnConnectDisplays.Margin = new Padding(2, 3, 2, 3);
            this.bnConnectDisplays.Name = "bnConnectDisplays";
            this.bnConnectDisplays.Size = new Size(0x38, 0x17);
            this.bnConnectDisplays.TabIndex = 0x23;
            this.bnConnectDisplays.Text = "Connect";
            this.bnConnectDisplays.UseVisualStyleBackColor = false;
            this.bnConnectDisplays.Visible = false;
            this.bnConnectDisplays.Click += new EventHandler(this.bnTest_Click);
            this.cbDisplayPortLeft.BackColor = Color.White;
            this.cbDisplayPortLeft.FormattingEnabled = true;
            this.cbDisplayPortLeft.Location = new System.Drawing.Point(0xbf, 0x1d);
            this.cbDisplayPortLeft.Margin = new Padding(2, 3, 2, 3);
            this.cbDisplayPortLeft.Name = "cbDisplayPortLeft";
            this.cbDisplayPortLeft.Size = new Size(60, 0x15);
            this.cbDisplayPortLeft.TabIndex = 0x22;
            this.cbDisplayPortLeft.Visible = false;
            this.cbLiveReport.AutoSize = true;
            this.cbLiveReport.Location = new System.Drawing.Point(0x143, 10);
            this.cbLiveReport.Margin = new Padding(2, 3, 2, 3);
            this.cbLiveReport.Name = "cbLiveReport";
            this.cbLiveReport.Size = new Size(0xb5, 0x11);
            this.cbLiveReport.TabIndex = 0x21;
            this.cbLiveReport.Text = "Report race data live to the web.";
            this.cbLiveReport.UseVisualStyleBackColor = true;
            this.cbLiveReport.CheckedChanged += new EventHandler(this.cbLiveReport_CheckedChanged);
            this.cbDisplayPortRight.BackColor = Color.White;
            this.cbDisplayPortRight.ForeColor = Color.Black;
            this.cbDisplayPortRight.FormattingEnabled = true;
            this.cbDisplayPortRight.Location = new System.Drawing.Point(0x101, 0x1d);
            this.cbDisplayPortRight.Margin = new Padding(2, 3, 2, 3);
            this.cbDisplayPortRight.Name = "cbDisplayPortRight";
            this.cbDisplayPortRight.Size = new Size(60, 0x15);
            this.cbDisplayPortRight.TabIndex = 0x26;
            this.cbDisplayPortRight.Visible = false;
            this.groupBox2.BackColor = Color.White;
            this.groupBox2.Controls.Add(this.cbLayOut);
            this.groupBox2.Controls.Add(this.cbWorkSheet);
            this.groupBox2.Controls.Add(this.cbRound);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Controls.Add(this.label1);
            this.groupBox2.Controls.Add(this.bnOpenWorkBook);
            this.groupBox2.Controls.Add(this.cbComPort);
            this.groupBox2.Controls.Add(this.tbFileName);
            this.groupBox2.Controls.Add(this.bnConnect);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.ForeColor = Color.Black;
            this.groupBox2.Location = new System.Drawing.Point(0, -2);
            this.groupBox2.Margin = new Padding(2, 3, 2, 3);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Padding = new Padding(2, 3, 2, 3);
            this.groupBox2.Size = new Size(0x175, 0x6c);
            this.groupBox2.TabIndex = 0x17;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Basic settings";
            this.cbLayOut.AutoSize = true;
            this.cbLayOut.Location = new System.Drawing.Point(0x102, 0x57);
            this.cbLayOut.Margin = new Padding(2, 3, 2, 3);
            this.cbLayOut.Name = "cbLayOut";
            this.cbLayOut.Size = new Size(0x49, 0x11);
            this.cbLayOut.TabIndex = 0x29;
            this.cbLayOut.Text = "Old layout";
            this.cbLayOut.UseVisualStyleBackColor = true;
            this.label7.AutoSize = true;
            this.label7.ForeColor = Color.Black;
            this.label7.Location = new System.Drawing.Point(0x16d, -1);
            this.label7.Margin = new Padding(2, 0, 2, 0);
            this.label7.Name = "label7";
            this.label7.Size = new Size(50, 13);
            this.label7.TabIndex = 0x18;
            this.label7.Text = "Reaction";
            this.label8.AutoSize = true;
            this.label8.ForeColor = Color.Black;
            this.label8.Location = new System.Drawing.Point(0x1be, -1);
            this.label8.Margin = new Padding(2, 0, 2, 0);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x33, 13);
            this.label8.TabIndex = 0x19;
            this.label8.Text = "Raw time";
            this.label9.AutoSize = true;
            this.label9.ForeColor = Color.Black;
            this.label9.Location = new System.Drawing.Point(540, -1);
            this.label9.Margin = new Padding(2, 0, 2, 0);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x25, 13);
            this.label9.TabIndex = 0x1a;
            this.label9.Text = "Cones";
            this.cbLeftCones.BackColor = Color.White;
            this.cbLeftCones.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cbLeftCones.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cbLeftCones.ForeColor = Color.Black;
            this.cbLeftCones.FormattingEnabled = true;
            object[] objArray3 = new object[] {
                "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15",
                "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "DQ"
            };
            this.cbLeftCones.Items.AddRange(objArray3);
            this.cbLeftCones.Location = new System.Drawing.Point(0x221, 14);
            this.cbLeftCones.Margin = new Padding(2, 3, 2, 3);
            this.cbLeftCones.Name = "cbLeftCones";
            this.cbLeftCones.Size = new Size(70, 0x20);
            this.cbLeftCones.TabIndex = 4;
            this.cbLeftCones.SelectionChangeCommitted += new EventHandler(this.LeftConesChanged);
            this.cbRightCones.BackColor = Color.White;
            this.cbRightCones.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cbRightCones.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cbRightCones.ForeColor = Color.Black;
            this.cbRightCones.FormattingEnabled = true;
            object[] objArray4 = new object[] {
                "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15",
                "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "DQ"
            };
            this.cbRightCones.Items.AddRange(objArray4);
            this.cbRightCones.Location = new System.Drawing.Point(0x220, 0x10);
            this.cbRightCones.Margin = new Padding(2, 3, 2, 3);
            this.cbRightCones.Name = "cbRightCones";
            this.cbRightCones.Size = new Size(70, 0x20);
            this.cbRightCones.TabIndex = 9;
            this.cbRightCones.SelectionChangeCommitted += new EventHandler(this.RightConesChanged);
            this.process1.StartInfo.Domain = "";
            this.process1.StartInfo.LoadUserProfile = false;
            this.process1.StartInfo.Password = null;
            this.process1.StartInfo.StandardErrorEncoding = null;
            this.process1.StartInfo.StandardOutputEncoding = null;
            this.process1.StartInfo.UserName = "";
            this.process1.SynchronizingObject = this;
            this.tbPrevData.Font = new System.Drawing.Font("Verdana", 11.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.tbPrevData.ForeColor = Color.Black;
            this.tbPrevData.Location = new System.Drawing.Point(8, 0x69);
            this.tbPrevData.Margin = new Padding(2, 3, 2, 3);
            this.tbPrevData.Multiline = true;
            this.tbPrevData.Name = "tbPrevData";
            this.tbPrevData.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.tbPrevData.Size = new Size(0x27c, 0x65);
            this.tbPrevData.TabIndex = 0x1d;
            this.tbPrevData.TabStop = false;
            this.tbPrevData.Visible = false;
            this.cbPreviousData.AutoSize = true;
            this.cbPreviousData.Font = new System.Drawing.Font("Microsoft Sans Serif", 8f);
            this.cbPreviousData.ForeColor = Color.Black;
            this.cbPreviousData.Location = new System.Drawing.Point(0x290, 0x57);
            this.cbPreviousData.Margin = new Padding(2, 3, 2, 3);
            this.cbPreviousData.Name = "cbPreviousData";
            this.cbPreviousData.Size = new Size(0x5e, 0x11);
            this.cbPreviousData.TabIndex = 0x1f;
            this.cbPreviousData.TabStop = false;
            this.cbPreviousData.Text = "show previous";
            this.cbPreviousData.UseVisualStyleBackColor = true;
            this.cbPreviousData.CheckedChanged += new EventHandler(this.cbPreviousData_CheckedChanged);
            this.bnReset.BackColor = Color.WhiteSmoke;
            this.bnReset.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.bnReset.ForeColor = Color.Black;
            this.bnReset.Location = new System.Drawing.Point(770, 8);
            this.bnReset.Margin = new Padding(2, 3, 2, 3);
            this.bnReset.Name = "bnReset";
            this.bnReset.Size = new Size(0x6c, 0x2b);
            this.bnReset.TabIndex = 11;
            this.bnReset.Text = "Reset/Start";
            this.bnReset.UseVisualStyleBackColor = false;
            this.bnReset.Click += new EventHandler(this.bnReset_Click);
            this.tabControl1.Controls.Add(this.tabSettings);
            this.tabControl1.Controls.Add(this.tabRace);
            this.tabControl1.Dock = DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(0, 0);
            this.tabControl1.Margin = new Padding(2, 3, 2, 3);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.Padding = new System.Drawing.Point(10, 3);
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new Size(0x37e, 0x88);
            this.tabControl1.TabIndex = 0x20;
            this.tabControl1.TabStop = false;
            this.tabControl1.SelectedIndexChanged += new EventHandler(this.tabControl1_SelectedIndexChanged);
            this.tabSettings.BackColor = Color.White;
            this.tabSettings.Controls.Add(this.groupBox1);
            this.tabSettings.Controls.Add(this.groupBox2);
            this.tabSettings.Location = new System.Drawing.Point(4, 0x16);
            this.tabSettings.Margin = new Padding(0);
            this.tabSettings.Name = "tabSettings";
            this.tabSettings.Size = new Size(0x376, 110);
            this.tabSettings.TabIndex = 0;
            this.tabSettings.Text = "Settings";
            this.tabRace.BackColor = Color.White;
            this.tabRace.Controls.Add(this.groupRight);
            this.tabRace.Controls.Add(this.groupLeft);
            this.tabRace.Controls.Add(this.bnRefreshList);
            this.tabRace.Controls.Add(this.bnReset);
            this.tabRace.Controls.Add(this.cbPreviousData);
            this.tabRace.Controls.Add(this.tbPrevData);
            this.tabRace.Controls.Add(this.bnSaveLeft);
            this.tabRace.Controls.Add(this.bnSaveRight);
            this.tabRace.Location = new System.Drawing.Point(4, 0x16);
            this.tabRace.Margin = new Padding(0);
            this.tabRace.Name = "tabRace";
            this.tabRace.Size = new Size(0x376, 110);
            this.tabRace.TabIndex = 1;
            this.tabRace.Text = "Race";
            this.groupRight.Controls.Add(this.cbRigthRider);
            this.groupRight.Controls.Add(this.tbRightReaction);
            this.groupRight.Controls.Add(this.tbRightRaw);
            this.groupRight.Controls.Add(this.label6);
            this.groupRight.Controls.Add(this.cbRightCones);
            this.groupRight.Controls.Add(this.label13);
            this.groupRight.Controls.Add(this.label14);
            this.groupRight.Location = new System.Drawing.Point(0, 0x34);
            this.groupRight.Margin = new Padding(0);
            this.groupRight.Name = "groupRight";
            this.groupRight.Padding = new Padding(0);
            this.groupRight.Size = new Size(0x284, 0x35);
            this.groupRight.TabIndex = 0x27;
            this.groupRight.TabStop = false;
            this.groupRight.Text = "Right";
            this.label6.AutoSize = true;
            this.label6.ForeColor = Color.Black;
            this.label6.Location = new System.Drawing.Point(0x21d, -1);
            this.label6.Margin = new Padding(2, 0, 2, 0);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x25, 13);
            this.label6.TabIndex = 0x22;
            this.label6.Text = "Cones";
            this.label13.AutoSize = true;
            this.label13.ForeColor = Color.Black;
            this.label13.Location = new System.Drawing.Point(0x1be, -1);
            this.label13.Margin = new Padding(2, 0, 2, 0);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x33, 13);
            this.label13.TabIndex = 0x21;
            this.label13.Text = "Raw time";
            this.label14.AutoSize = true;
            this.label14.ForeColor = Color.Black;
            this.label14.Location = new System.Drawing.Point(0x16e, -1);
            this.label14.Margin = new Padding(2, 0, 2, 0);
            this.label14.Name = "label14";
            this.label14.Size = new Size(50, 13);
            this.label14.TabIndex = 0x20;
            this.label14.Text = "Reaction";
            this.groupLeft.Controls.Add(this.cbLeftRider);
            this.groupLeft.Controls.Add(this.tbLeftRaw);
            this.groupLeft.Controls.Add(this.cbLeftCones);
            this.groupLeft.Controls.Add(this.tbLeftReaction);
            this.groupLeft.Controls.Add(this.label7);
            this.groupLeft.Controls.Add(this.label8);
            this.groupLeft.Controls.Add(this.label9);
            this.groupLeft.Location = new System.Drawing.Point(0, 0);
            this.groupLeft.Margin = new Padding(0);
            this.groupLeft.Name = "groupLeft";
            this.groupLeft.Padding = new Padding(0);
            this.groupLeft.Size = new Size(0x284, 0x35);
            this.groupLeft.TabIndex = 0x26;
            this.groupLeft.TabStop = false;
            this.groupLeft.Text = "Left";
            this.bnRefreshList.Location = new System.Drawing.Point(770, 0x54);
            this.bnRefreshList.Margin = new Padding(2, 3, 2, 3);
            this.bnRefreshList.Name = "bnRefreshList";
            this.bnRefreshList.Size = new Size(0x6d, 0x13);
            this.bnRefreshList.TabIndex = 0x25;
            this.bnRefreshList.TabStop = false;
            this.bnRefreshList.Text = "Refresh racers";
            this.bnRefreshList.UseVisualStyleBackColor = true;
            this.bnRefreshList.Click += new EventHandler(this.bnRefreshList_Click);
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.White;
            base.ClientSize = new Size(0x37e, 0x88);
            base.Controls.Add(this.tabControl1);
            this.ForeColor = Color.Black;
            base.FormBorderStyle = FormBorderStyle.FixedSingle;
            base.Icon = (Icon)manager.GetObject("$this.Icon");
            base.Margin = new Padding(2, 3, 2, 3);
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "mExcelMate";
            this.Text = "Excelmate - Trackmate reader for skateboard slalom racing v5.3 - build 2017 08 14";
            base.FormClosing += new FormClosingEventHandler(this.ExcelMate_FormClosing);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.tabControl1.ResumeLayout(false);
            this.tabSettings.ResumeLayout(false);
            this.tabRace.ResumeLayout(false);
            this.tabRace.PerformLayout();
            this.groupRight.ResumeLayout(false);
            this.groupRight.PerformLayout();
            this.groupLeft.ResumeLayout(false);
            this.groupLeft.PerformLayout();
            base.ResumeLayout(false);
        }

        #endregion


        private System.Windows.Forms.CheckBox cbColors;
        private System.Windows.Forms.Button bnHelp;
        private System.Windows.Forms.TextBox tbReporterId;
        private System.Windows.Forms.TextBox tbEventId;

        private System.Windows.Forms.Button bnSaveLeft;
        private System.Windows.Forms.TextBox tbLeftRaw;
        private System.Windows.Forms.OpenFileDialog openFileDialog1;
        private System.Windows.Forms.Button bnOpenWorkBook;
        private System.Windows.Forms.TextBox tbFileName;
        private System.Windows.Forms.ComboBox cbWorkSheet;
        private System.Windows.Forms.ComboBox cbRound;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.ComboBox cbLeftRider;
        private System.Windows.Forms.TextBox tbLeftReaction;
        private System.Windows.Forms.TextBox tbRightReaction;
        private System.Windows.Forms.ComboBox cbRigthRider;
        private System.Windows.Forms.Button bnSaveRight;
        private System.Windows.Forms.TextBox tbRightRaw;
        private System.Windows.Forms.ComboBox cbComPort;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Button bnConnect;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.ComboBox cbLeftCones;
        private System.Windows.Forms.ComboBox cbRightCones;
        private System.Diagnostics.Process process1;
        private System.Windows.Forms.CheckBox cbPreviousData;
        private System.Windows.Forms.TextBox tbPrevData;
        private System.Windows.Forms.Button bnReset;
        private System.Windows.Forms.CheckBox cbDisplays;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabSettings;
        private System.Windows.Forms.TabPage tabRace;
        private System.Windows.Forms.ComboBox cbDisplayPortLeft;
        private System.Windows.Forms.Button bnConnectDisplays;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.ComboBox cbDisplayPortRight;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.TextBox tbLiveId;
        private System.Windows.Forms.CheckBox cbLiveReport;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.TextBox tbLiveEventId;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.CheckBox cbLayOut;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Button bnCheckId;
        private System.Windows.Forms.CheckBox cbDiscardReactionTimes;
        private System.Windows.Forms.Button bnRefreshList;
        private System.Windows.Forms.CheckBox cbSingleLanePort;
        private System.Windows.Forms.ComboBox cbLeftColor;
        private System.Windows.Forms.ComboBox cbRightColor;
        private System.Windows.Forms.CheckBox cbLog2File;
        private System.Windows.Forms.CheckBox cbColor;
        private System.Windows.Forms.GroupBox groupRight;
        private System.Windows.Forms.GroupBox groupLeft;
        private System.Windows.Forms.Button button1;
    }
}

